version: '3'

services:
  rancher-server:
    image: rancher/rancher:latest
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CATTLE_SYSTEM_CATALOG=bundled
    volumes:
      - rancher-data:/var/lib/rancher

volumes:
  rancher-data:
